import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import rtl from "rtl-detect";
import { SupportedLanguage } from "@/locales/.generated/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    lang: SupportedLanguage;
  }>;
}>) {
  const { lang } = await params;
  return (
    <html lang={lang} dir={rtl.getLangDir(lang)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
